# Site
name: "Feezify.me"
description: "Feezify.me c'est une application et un blog pour vous aider à optimisez votre récupération physique et mentale."
meta_description: "Le blog pour vous aider à optimisez votre récupération physique et mentale: Running - Trail - Triathlon - Cyclisme - VTT - Randonnée - Marche. Feezify.me"
meta_keywords: "entrainement, carnet d'entrainement, suivi d'entrainement, running, course à pied, cyclisme, natation, vtt, entrainement, entrainement running, entrainement course à pied, entrainement cyclisme, entrainement natation, entrainement vtt"
logo: 'assets/images/brand/logo.png'

# baseurl: 
google_analytics: 'UA-119879264-1'
disqus: 'randovttbretagne'
facebookpage_id: 502710249769535
facebook_article_author: 10210003510697734
facebook_article_publisher: https://www.facebook.com/app.vtt.bzh
google_verification: 
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'


permalink: /:title:output_ext

# Authors
authors:
  nicolas:
    name: Nicolas
    display_name: "Nicolas Jouanno"
    avatar: https://miro.medium.com/fit/c/240/240/1*Tysig6P_3bP56CAs-TsxNA.png
    email: nicolas@feezify.me
    web: https://www.linkedin.com/in/nicolasjouanno/
    twitter: https://twitter.com/nicolasjouanno
    twitter_creator: "@nicolasjouanno"
    twitter_site: "@VTT_bzh"
    description: "Ancien cycliste professionnel, je suis maintenant un vrai touche à tout: cyclisme bien sûr, mais aussi running, natation, surf, fitness, randonnée, triathlon et bien d'autres. Chaque sport m'apporte énormément sur les plans: physique, mental et humain. Abonne toi à ma newsletter pour en savoir plus."
    google_plus: https://plus.google.com/u/0/101743465600034380035
    mediumcom_creator : "https://medium.com/@nicolasjouanno"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge