# Site
name: "Feezify.me"
description: "Optimisez votre récupération physique et psychologique."
meta_description: "Application de gestion d'entrainement sportif: Running - Trail - Triathlon - Cyclisme - VTT - Randonnée - Marche. Feezify.me"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
# baseurl: 
google_analytics: 'UA-119879264-1'
disqus: 'vtt_bzh'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'


permalink: /:title:output_ext

# Authors
authors:
  nicolas:
    name: Nicolas
    display_name: Nicolas
    avatar: https://miro.medium.com/fit/c/240/240/1*Tysig6P_3bP56CAs-TsxNA.png
    email: nicolas@feezify.me
    web: https://www.linkedin.com/in/nicolasjouanno/
    twitter: https://twitter.com/nicolasjouanno
    description: "A great Product is better than Marketing | 🚀 | addict: #sport #startup 💼 | skills: #webdevelopment #productManagement #growthHacking 👾"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge